SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '[aeiouAEIOU]$';

SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[aeiouAEIOU]';

SELECT CITY, LENGTH(CITY) AS name_length
FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1;
SELECT CITY, LENGTH(CITY) AS name_length
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY
LIMIT 1;

SELECT COUNT(CITY) - COUNT(DISTINCT CITY) AS difference
FROM STATION;

SELECT DISTINCT CITY
FROM STATION
WHERE ID % 2 = 0;

SELECT CITY, STATE
FROM STATION;

SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT *
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT *
FROM CITY
WHERE ID = 1661;

SELECT *
FROM CITY;

SELECT NAME
FROM CITY
WHERE CountryCode = 'USA'
AND Population > 120000;

SELECT NAME
FROM CITY
WHERE CountryCode = 'USA'
AND Population > 120000;

SELECT *
FROM CITY
WHERE CountryCode = 'USA'
AND Population > 100000;

